### ISSUE TITLE
Remaining estimate can't be updated from jira-time

### ISSUE THREAD

**Issue by KasperTraczyk** [hkhesehus/jira-time#46]
The input field won't allow changes to remaining estimate. This used to work fine.

**Comment by hkhesehus** [comment]
This happens due to an update I did today; I set changed input field for the remaining estimate from:
`<input defaultValue={remainingEstimate} />`
to
`<input value={remainingEstimate} />`

The latter makes the input field update whenever the redux state is updated (which might be once every second for the active recorder item. Looking into how to get around this.

**Comment by hkhesehus** [comment]
Solved (at least on my mac) by separating the task item and its records. Now, when a record item updates its remaining time, the task item stays untouched.

**Comment by hkhesehus** [comment]
Fixed
